version: '2'
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=userpass
      - POSTGRES_USER=user
      - POSTGRES_DB=db
    ports:
      - '127.0.0.1:5432:5432'
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_PASSWORD=userpass
      - MYSQL_USER=user
      - MYSQL_DATABASE=db
    ports:
      - "127.0.0.1:3306:3306"