version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
        environment:
          PIPENV_VENV_IN_PROJECT: 1

    steps:
      - checkout

      - run: 
          command: |
            echo hello